name: ai_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.18
  url_launcher: ^6.2.6
  yaml: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/conversation_ai_simple.json
    - assets/data/text_ai_simple.json
    - assets/data/image_ai_simple.json
    - assets/data/sound_ai_simple.json
    - assets/data/programming_ai_simple.json
    - assets/data/movie_ai_simple.json
    - assets/data/data_ai_simple.json
    - assets/data/categories.json
    - assets/ai_details_md/
    - assets/seven_icons/
    - assets/ai_icons/